version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: cloudws
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: passsword
      - image: circleci/mysql:5.7.24
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Install openjdk-8 and maven
          command: |
            apt-get -y update
            apt-get -y upgrade
            apt-get install -y openjdk-8-jdk
            apt-get install -y maven
      - run:
          name: create mysql database (cloudws)
          command: |
            apt-get install -y mysql-client
            mysql -h 127.0.0.1 -u root -e "create database cloudws;"
      - run:
          name: build cloudws project.
          command: mvn clean install

