version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
      - image: circleci/mysql:5.7.24
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: cloudws
          MYSQL_ROOT_HOST: 127.0.0.1
          MYSQL_USER: root
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get -y update
            apt-get -y upgrade
            apt-get install -y openjdk-8-jdk
            apt-get install -y maven
      - run:
          name: Build cloudws project.
          command: mvn clean install

