version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install jPython deps in a venv
            command: |
              apt-get update
              apt-get upgrade
              apt-get install openjdk-8-jdk
