version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install openjdk-8
          command: |
            apt-get -y update
            apt-get -y upgrade
            apt-get install -y openjdk-8-jdk
